[workspace]

members = [
    "quantum_launcher",
    "crates/ql_instances",
    "crates/ql_mod_manager",
    "crates/ql_core",
    "crates/omniarchive_api",
    "crates/ql_servers",
]

# [profile.dev]
# opt-level = 1

[profile.dev.package."*"]
opt-level = 3
debug = false
