[package]
name = "quantum_launcher"
version = "0.3.0"
edition = "2021"

authors = ["Mrmayman <navneetkrishna22@gmail.com>"]
description = "A simple Minecraft Launcher written in Rust."
keywords = ["minecraft", "mc", "launcher"]
license = "GPL-3.0-only"
repository = "https://github.com/Mrmayman/quantum-launcher/"
readme = "../README.md"

build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
embed-resource = "3"

[dependencies]
ql_instances = { path = "../crates/ql_instances" }
ql_mod_manager = { path = "../crates/ql_mod_manager" }
ql_core = { path = "../crates/ql_core" }

# For the GUI
iced = { version = "0.12", features = ["tokio", "image"] }

# For parsing JSON
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# For managing async tasks
tokio = { version = "1", features = ["fs"] }
# For colored text output
colored = "2"
# For managing the logging time/date
chrono = "0.4"
# For the icon widget macro
paste = "1"
# For the global style variable
lazy_static = "1"
# For the file picker
rfd = "0.15"

comrak = "0.28" # For markdown parsing (displaying mod pages)
image = "0.24"
# We be implementing a full blown HTML renderer in iced with this one
html5ever = "0.27"
markup5ever_rcdom = "0.3"
