[package]
name = "quantum_launcher"
version = "0.1.0"
edition = "2021"

authors = ["Mrmayman <navneetkrishna22@gmail.com>"]
description = "A simple Minecraft Launcher written in Rust."
keywords = ["minecraft", "mc", "launcher"]
license = "GPL-3.0-only"
repository = "https://github.com/Mrmayman/quantum-launcher-rs/"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ql_instances = { path = "../ql_instances" }
ql_mod_manager = { path = "../ql_mod_manager" }

# For the GUI
iced = { version = "0.12", features = ["highlighter", "tokio", "image"] }

# For parsing JSON
serde = { version = "1", features = ["derive"] }
serde_json = "1"

tokio = "1"      # For managing async tasks
colored = "2"    # For colored text output
chrono = "0.4"   # For managing the logging time/date
paste = "1.0.15" # For the icon widget macro

comrak = "0.28.0" # For markdown parsing (displaying mod pages)

# We be implementing a full blown HTML renderer in iced with this one
html5ever = "0.26.0"
markup5ever_rcdom = "0.2.0"
