[package]
name = "quantum_launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quantum_launcher_backend = { path = "../quantum_launcher_backend" }
pollster = "*"
