[package]
name = "ql_core"
version = "0.3.1"
edition = "2021"

[dependencies]
chrono = "0.4"
colored = "2"
dirs = "5"
futures = "0.3"
lazy_static = "1"
reqwest = "0.12"
serde = "1"
serde_json = "1"
zip-extract = "0.1"

# For finding the closest official version to
# an Omniarchive version.
strsim = "0.11"

# For extracting aarch64 java.
flate2 = "1"
tar = "0.4"
