[package]
name = "ql_core"
version = "0.4.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
dirs = "5"
futures = "0.3"
zip-extract = { workspace = true }

colored = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }

# For finding the closest official version to
# an Omniarchive version.
strsim = "0.11"
