[package]
name = "omniarchive_api"
version = "0.1.0"
edition = "2021"

[dependencies]
ql_core = { path = "../ql_core" }

colored = { workspace = true }
thiserror = { workspace = true }

# HTML Parsing
html5ever = { workspace = true }
markup5ever_rcdom = { workspace = true }
