[package]
name = "ql_core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
colored = "2"
dirs = "5"
futures = "0.3"
lazy_static = "1"
reqwest = { version = "0.12" }
serde = "1"
serde_json = "1"
